import Foundation
import Testing
@testable import ClipjarCore

@Suite struct ClipFilterTests {
    private let onePassword = SourceApp(bundleID: "com.1password.1password", name: "1Password")

    private func decide(
        _ types: Set<String> = [PasteboardTypes.string],
        candidates: [SourceApp] = [textEdit],
        settings: FilterSettings = FilterSettings(),
        now: Date = t0
    ) -> FilterDecision {
        ClipFilter.preflight(
            types: types, candidates: candidates, settings: settings,
            ownBundleID: AppIdentity.bundleID, now: now
        )
    }

    @Test func markerWinsOverEverything() {
        let decision = decide(
            [PasteboardTypes.marker, PasteboardTypes.concealed],
            candidates: [onePassword],
            settings: FilterSettings(isPaused: true)
        )
        #expect(decision == .reject(.ownWrite))
    }

    @Test func pausedIndefinitely() {
        #expect(decide(settings: FilterSettings(pausedUntil: nil, isPaused: true)) == .reject(.paused))
    }

    @Test func pausedUntilFuture() {
        let settings = FilterSettings(pausedUntil: t0.addingTimeInterval(60), isPaused: true)
        #expect(decide(settings: settings) == .reject(.paused))
    }

    @Test func pausedUntilPast() {
        let settings = FilterSettings(pausedUntil: t0.addingTimeInterval(-60), isPaused: true)
        #expect(decide(settings: settings) == .accept)
    }

    @Test func concealed() {
        #expect(decide([PasteboardTypes.string, PasteboardTypes.concealed]) == .reject(.concealed))
    }

    @Test(arguments: SensitiveTypes.all.sorted())
    func sensitiveTypes(_ type: String) {
        #expect(decide([PasteboardTypes.string, type]) == .reject(.concealed))
    }

    @Test func transient() {
        #expect(decide([PasteboardTypes.string, PasteboardTypes.transient]) == .reject(.transient))
    }

    @Test func autoGenerated() {
        #expect(decide([PasteboardTypes.string, PasteboardTypes.autoGen]) == .reject(.autoGenerated))
    }

    @Test func concealedBeatsTransient() {
        #expect(decide([PasteboardTypes.concealed, PasteboardTypes.transient]) == .reject(.concealed))
    }

    @Test(arguments: [0, 1, 2])
    func ignoredCandidateAnyPosition(_ position: Int) {
        var candidates = [textEdit, safari, SourceApp(bundleID: "com.example.editor", name: "Editor")]
        candidates[position] = onePassword
        #expect(decide(candidates: candidates) == .reject(.ignoredApp))
    }

    @Test func passwordsAppIgnoredByDefault() {
        let passwords = SourceApp(bundleID: "com.apple.Passwords", name: "Passwords")
        #expect(decide(candidates: [passwords]) == .reject(.ignoredApp))
    }

    @Test func ownBundleIDRejected() {
        let clipjar = SourceApp(bundleID: AppIdentity.bundleID, name: "Clipjar")
        #expect(decide(candidates: [clipjar]) == .reject(.ignoredApp))
    }

    @Test func nilBundleIDsAccepted() {
        #expect(decide(candidates: [SourceApp(bundleID: nil, name: nil)]) == .accept)
    }

    @Test func defaults() {
        let settings = FilterSettings()
        #expect(settings.ignoredBundleIDs == [
            "com.apple.keychainaccess", "com.apple.Passwords", "com.1password.1password", "com.agilebits.onepassword7",
        ])
        #expect(settings.maxTextBytes == 1_000_000)
        #expect(settings.maxImageBytes == 20_000_000)
        #expect(FilterSettings.maxRichBytes == 2_000_000)
        #expect(!settings.isPaused)
        #expect(settings.pausedUntil == nil)
    }
}
