import Foundation

public struct FilterSettings: Sendable, Equatable {
    public static let defaultIgnoredBundleIDs: Set<String> = [
        "com.apple.keychainaccess", "com.apple.Passwords", "com.1password.1password", "com.agilebits.onepassword7",
    ]
    public static let maxRichBytes = 2_000_000

    public var ignoredBundleIDs: Set<String>
    public var pausedUntil: Date?
    public var isPaused: Bool
    public var maxTextBytes: Int
    public var maxImageBytes: Int

    public init(
        ignoredBundleIDs: Set<String> = defaultIgnoredBundleIDs,
        pausedUntil: Date? = nil,
        isPaused: Bool = false,
        maxTextBytes: Int = 1_000_000,
        maxImageBytes: Int = 20_000_000
    ) {
        self.ignoredBundleIDs = ignoredBundleIDs
        self.pausedUntil = pausedUntil
        self.isPaused = isPaused
        self.maxTextBytes = maxTextBytes
        self.maxImageBytes = maxImageBytes
    }
}

public enum FilterDecision: Equatable, Sendable {
    case accept
    case reject(Reason)

    public enum Reason: Sendable, Equatable {
        case ownWrite, paused, concealed, transient, autoGenerated, ignoredApp, oversized, empty
    }
}

public enum ClipFilter {
    /// Decides from pasteboard type metadata and candidate apps alone; first matching rule wins.
    public static func preflight(
        types: Set<String>,
        candidates: [SourceApp],
        settings: FilterSettings,
        ownBundleID: String,
        now: Date
    ) -> FilterDecision {
        if types.contains(PasteboardTypes.marker) { return .reject(.ownWrite) }
        if settings.isPaused, settings.pausedUntil.map({ now < $0 }) ?? true { return .reject(.paused) }
        if types.contains(PasteboardTypes.concealed) || !types.isDisjoint(with: SensitiveTypes.all) {
            return .reject(.concealed)
        }
        if types.contains(PasteboardTypes.transient) { return .reject(.transient) }
        if types.contains(PasteboardTypes.autoGen) { return .reject(.autoGenerated) }
        let ignored = candidates.contains { app in
            guard let id = app.bundleID else { return false }
            return id == ownBundleID || settings.ignoredBundleIDs.contains(id)
        }
        return ignored ? .reject(.ignoredApp) : .accept
    }
}
