import Foundation

public enum PasteboardTypes {
    /// Added to every pasteboard write Clipjar makes, so the watcher never captures its own writes.
    public static let marker = "com.vtrifonov.clipjar.marker"
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGen = "org.nspasteboard.AutoGeneratedType"
    public static let source = "org.nspasteboard.source"
    public static let fileURL = "public.file-url"
    public static let string = "public.utf8-plain-text"
    public static let rtf = "public.rtf"
    public static let html = "public.html"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
}

/// Vendor-specific markers for password-manager and generated content.
public enum SensitiveTypes {
    public static let all: Set<String> = [
        "com.agilebits.onepassword", "net.antelle.keeweb", "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping", "Pasteboard generator type",
    ]
}
